version: "3.3"

networks:
  app-tier:
    driver: bridge

services:
  server:
    container_name: server

    depends_on:
      - db

    build:
      context: ./server
      dockerfile: Dockerfile
      # target: base

    networks:
      - app-tier

    volumes:
      - ./server/src:/home/node/server/src
      - ./server/logs:/home/node/server/logs
      - ./server/nodemon.json:/home/node/server/nodemon.json
      - ./server/package.json:/home/node/server/package.json
      - ./server/ormconfig.ts:/home/node/server/ormconfig.ts
      - ./server/tsconfig.json:/home/node/server/tsconfig.json
      - ./server/node_modules:/home/node/server/node_modules

    links:
      - db

    expose:
      - "8000"

    ports:
      - "8000:8000"

    command: yarn dev

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
      # PORT
      MYSQL_TCP_PORT: 3307
      # VIRTUAL_PORT
      VIRTUAL_PORT: 3307
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3307:3307"
    expose:
      # Opens port 3307 on the container
      - "3307"
    networks:
      - app-tier
    # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
